School: main.cpp names.cpp senior.cpp junior.cpp student.cpp teacher.cpp human.cpp corridor.cpp stairs.cpp yard.cpp waiting_room.cpp classroom.cpp floor.cpp school.cpp
	g++ -o School main.cpp names.cpp senior.cpp junior.cpp student.cpp teacher.cpp human.cpp corridor.cpp stairs.cpp yard.cpp 		waiting_room.cpp classroom.cpp floor.cpp school.cpp

clean: 
	-rm -f *.o 
	-rm School
